import advancedKneeOa1 from '../assets/service/advanced-treatment-for-knee-osteoarthritis-and-cartilage-wearing_1.png';
import advancedKneeOa2 from '../assets/service/advanced-treatment-for-knee-osteoarthritis-and-cartilage-wearing_2.png';
import plantarFasciitis1 from '../assets/service/clinical-treatment-for-plantar-fasciitis-and-morning-heel-pain_1.png';
import plantarFasciitis2 from '../assets/service/clinical-treatment-for-plantar-fasciitis-and-morning-heel-pain_2.png';
import plantarFasciitis3 from '../assets/service/clinical-treatment-for-plantar-fasciitis-and-morning-heel-pain_3.png';
import respiratoryCare1 from '../assets/service/holistic-upper-respiratory-immunity-and-throat-care_1.png';
import respiratoryCare2 from '../assets/service/holistic-upper-respiratory-immunity-and-throat-care_2.png';
import jointRehab1 from '../assets/service/non-surgical-advanced-joint-and-slip-disc-rehabilitation_1.png';
import jointRehab2 from '../assets/service/non-surgical-advanced-joint-and-slip-disc-rehabilitation_2.png';
import varicoseVeins1 from '../assets/service/permanent-treatment-for-varicose-veins-and-blood-congestion_1.png';
import varicoseVeins2 from '../assets/service/permanent-treatment-for-varicose-veins-and-blood-congestion_2.png';
import eczema1 from '../assets/service/root-cause-ayurvedic-management-for-stubborn-eczema-and-skin-allergies_1.png';
import eczema2 from '../assets/service/root-cause-ayurvedic-management-for-stubborn-eczema-and-skin-allergies_2.png';
import eczema3 from '../assets/service/root-cause-ayurvedic-management-for-stubborn-eczema-and-skin-allergies_3.png';
import eczema4 from '../assets/service/root-cause-ayurvedic-management-for-stubborn-eczema-and-skin-allergies_4.png';
import shirodhara1 from '../assets/service/soothing-shirodhara-treatment-for-corporate-stress-and-insomnia_1.png';
import shirodhara2 from '../assets/service/soothing-shirodhara-treatment-for-corporate-stress-and-insomnia_2.png';

const servicesData = [
    {
        "slug": "non-surgical-advanced-joint-and-slip-disc-rehabilitation",
        "groupSlug": "orthopedics-non-surgical-pain-management",
        "title": "Non-Surgical Advanced Joint and Slip Disc Rehabilitation",
        "shortDescription": "Are you suffering from debilitating lower back pain, a painful slipped disc, or severe joint stiffness that...",
        "description": "Are you suffering from debilitating lower back pain, a painful slipped disc, or severe joint stiffness that completely limits your physical freedom? Many chronic pain sufferers across Kolkata assume that invasive spinal surgeries or long-term painkiller management are their only paths to relief, but authentic Ayurvedic medical science provides a highly effective, non-surgical solution. At Swasthyaveda Healthcare clinic in Lake Town, Kolkata, Dr. Purva Verma utilizes advanced Viddhakarma therapy to treat complex orthopedic disorders. Viddhakarma is an ancient, highly precise Marma needling technique that decompresses irritated nerve roots, drains localized tissue inflammation, and releases rigid muscle spasms instantly. We pair this with Kati Basti, where a continuous pool of warm, customized medicated oils is retained over the lumbar spine to deeply nourish dry spinal discs, enhance local circulation, and rebuild surrounding muscle strength naturally. Dr. Purva Verma, a Gold Medalist graduate, combines deep structural knowledge with authentic Panchakarma protocols to target the root mechanical cause of your pain rather than just masking the symptoms. Stop letting chronic joint stiffness control your career or family life. Experience authentic, results-driven medical Ayurveda in North Kolkata. Reclaim full spinal flexibility, restore painless joint mobility, and return to an active, drug-free life safely under the guidance of an MD Ayurveda specialist.",
        "highlights": [],
        "images": [jointRehab1, jointRehab2]
    },
    {
        "slug": "root-cause-ayurvedic-management-for-stubborn-eczema-and-skin-allergies",
        "groupSlug": "skin-hair-advanced-blood-purification",
        "title": "Root-Cause Ayurvedic Management for Stubborn Eczema and Skin Allergies",
        "shortDescription": "Living with the constant burden of weeping eczema, intense skin itching, scaling, and painful rashes can be...",
        "description": "Living with the constant burden of weeping eczema, intense skin itching, scaling, and painful rashes can be incredibly exhausting, especially when temporary steroid creams no longer provide relief. In the traditional Ayurvedic medical framework, chronic skin disorders are not merely surface issues; they indicate an accumulation of deep-seated metabolic toxins mixed with heavily vitiated Pitta dosha and contaminated blood tissues. At Swasthyaveda Healthcare clinic in Lake Town, Kolkata, Dr. Purva Verma provides a comprehensive internal and external detoxification protocol. Our clinical dermatology treatments utilize advanced blood purification methods like Siraveda (therapeutic bloodletting) to directly remove localized circulatory toxins, combined with the precise application of cooling medicated herbal pastes known as Sthanika Lepam. This dual-action methodology draws out deep-seated inflammation, reduces intense dermal burning, and stimulates rapid cellular repair of the skin layers naturally without any harsh chemical dependencies. Dr. Purva Verma, a Gold Medalist graduate, customizes every skin rehabilitation package according to your individual body type to ensure long-term structural healing and glowing skin health. Discover a permanent path to pure, allergy-free skin right here in North Kolkata near Laketown Yes Bank. Flush out deep dermal toxins, restore your skin's natural protective barrier, and experience lasting relief from chronic allergies under an expert doctor.",
        "highlights": [],
        "images": [eczema1, eczema2, eczema3, eczema4]
    },
    {
        "slug": "holistic-upper-respiratory-immunity-and-throat-care",
        "groupSlug": "eye-ear-head-rejuvenation",
        "title": "Holistic Upper Respiratory Immunity and Throat Care",
        "shortDescription": "Observing World Head and Neck Cancer Day reminds us of the critical importance of maintaining optimal upper...",
        "description": "Observing World Head and Neck Cancer Day reminds us of the critical importance of maintaining optimal upper respiratory health and protecting our delicate mucosal linings from modern urban pollution, toxic smoking hazards, and chronic cellular inflammation. At Swasthyaveda Healthcare clinic in Lake Town, Kolkata, Dr. Purva Verma utilizes targeted Ayurvedic therapies to deeply cleanse and strengthen the entire upper respiratory tract. Our clinical protocols feature authentic Dhoompan, a precise medicated smoke inhalation therapy that utilizes sterile, natural herbal formulations to liquefy stagnant Kapha blocks, soothe persistent throat irritation, and drain toxic accumulations from the nasal cavities. This is combined with Nasya, where personalized medicated herbal drops are administered directly through the nasal passage to nourish the brain, strengthen the cervical nerve endings, and boost cellular immunity across the head and neck region. Dr. Purva Verma, a Gold Medalist holding an MD in Ayurveda, carefully monitors your health mapping to safeguard your respiratory tract against seasonal allergies, chronic tonsillitis, and toxic environmental damage. Prioritize your long-term wellness and build a robust structural shield for your respiratory system naturally without chemical side effects. Cleanse your respiratory channels, safeguard your upper body immunity, and breathe comfortably under the guidance of a trusted alternative medicine specialist.",
        "highlights": [],
        "images": [respiratoryCare1, respiratoryCare2]
    },
    {
        "slug": "soothing-shirodhara-treatment-for-corporate-stress-and-insomnia",
        "groupSlug": "stress-sleep-mental-wellness",
        "title": "Soothing Shirodhara Treatment for Corporate Stress and Insomnia",
        "shortDescription": "Is a high-pressure corporate career, constant digital overload, or nagging anxiety keeping you tossing and turning...",
        "description": "Is a high-pressure corporate career, constant digital overload, or nagging anxiety keeping you tossing and turning all night? Chronic insomnia, brain fog, and severe nervous exhaustion can completely damage your body's physical immunity, cardiac functions, and long-term mental peace. If you are struggling to fall asleep or constantly feeling emotionally overwhelmed, discover the ultimate stress-elimination therapy: authentic Shirodhara. At Swasthyaveda Healthcare clinic in Lake Town, Kolkata, Dr. Purva Verma specializes in this deeply tranquilizing clinical procedure. Shirodhara involves pouring a continuous, mathematically precise stream of warm, customized medicated herbal oil over the forehead to activate vital cranial Marma points. This deep action directly calms the sympathetic nervous system, drops elevated cortisol levels, eliminates mental fatigue, and fully restores deep, natural sleep cycles effortlessly without habit-forming sleeping pills. Dr. Purva Verma combines this powerful head pouring treatment with authentic full-body oil massages (Abhyangam) to pull deep-seated stress entirely out of your muscles. Reclaim your baseline mental clarity, build high stress-resilience, and enjoy peaceful nights at North Kolkata's leading wellness center near Laketown Yes Bank. Calm your overactive mind, rejuvenate your nervous system, and experience profound nightly rest under the care of an MD Ayurveda expert.",
        "highlights": [],
        "images": [shirodhara1, shirodhara2]
    },
    {
        "slug": "clinical-treatment-for-plantar-fasciitis-and-morning-heel-pain",
        "groupSlug": "orthopedics-non-surgical-pain-management",
        "title": "Clinical Treatment for Plantar Fasciitis and Morning Heel Pain",
        "shortDescription": "Are you experiencing an excruciating, sharp pain in your heel every single morning when you take your first steps...",
        "description": "Are you experiencing an excruciating, sharp pain in your heel every single morning when you take your first steps out of bed? This painful condition is classic plantar fasciitis or a calcaneal spur, caused by chronic micro-tears, calcium deposition, and localized tissue inflammation in the plantar fascia tendon. While standard orthopedic care often involves temporary cortisone injections or complex surgical recommendations, authentic Ayurveda provides an instant, non-surgical path to permanent recovery. At Swasthyaveda Healthcare clinic in Lake Town, Kolkata, Dr. Purva Verma specializes in advanced Agnikarma therapy for heel pain. Agnikarma is a precise thermal micro-cauterization procedure that applies calculated, therapeutic heat directly to the painful heel coordinates. This advanced clinical action instantly neutralizes deep-seated inflammation, removes localized blood congestion, increases tissue vascularity, and stimulates rapid cellular repair in the damaged tendons. Dr. Purva Verma, a Gold Medalist graduate, pairs Agnikarma with specialized Vata-balancing herbal poultices to ensure complete joint and tendon rehabilitation. Stop letting nagging heel stiffness restrict your daily movement and career focus. Visit our clean, professional alternative medicine clinic near Green View Apartment. Eliminate localized tendon inflammation, restore complete walking flexibility, and reclaim pain-free steps naturally without surgical interventions.",
        "highlights": [],
        "images": [plantarFasciitis1, plantarFasciitis2, plantarFasciitis3]
    },
    {
        "slug": "permanent-treatment-for-varicose-veins-and-blood-congestion",
        "groupSlug": "skin-hair-advanced-blood-purification",
        "title": "Permanent Treatment for Varicose Veins and Blood Congestion",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Jalaukavacharana (Leech Therapy) for vascular pooling and localized leg pain. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue-nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": [varicoseVeins1, varicoseVeins2]
    },
    {
        "slug": "advanced-treatment-for-knee-osteoarthritis-and-cartilage-wearing",
        "groupSlug": "eye-ear-head-rejuvenation",
        "title": "Advanced Treatment for Knee Osteoarthritis & Cartilage Wearing",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Janu Basti knee joint oil pooling to regenerate lost synovial fluid naturally. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue-nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": [advancedKneeOa1, advancedKneeOa2]
    },
    {
        "slug": "deep-panchakarma-colon-cleanse-for-systemic-detoxification",
        "groupSlug": "digestive-detox-lifestyle-management",
        "title": "Deep Panchakarma Colon Cleanse for Systemic Detoxification",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Basti treatment to flush accumulated metabolic toxins (Ama) out of the body. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue-nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "clinical-management-for-irritable-bowel-syndrome-and-acidity",
        "groupSlug": "digestive-detox-lifestyle-management",
        "title": "Clinical Management for Irritable Bowel Syndrome & Acidity",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Balancing the internal metabolic fire (Agni) via custom herbal formulations. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue-nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "treatment-for-dry-eyes-and-digital-ocular-fatigue",
        "groupSlug": "eye-ear-head-rejuvenation",
        "title": "Treatment for Dry Eyes and Digital Ocular Fatigue",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Netra Tarpana eye treatment to soothe digital eye strain for IT professionals. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "natural-weight-loss-therapy-and-cellulite-reduction",
        "groupSlug": "digestive-detox-lifestyle-management",
        "title": "Natural Weight Loss Therapy & Cellulite Reduction",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Udwartana dry deep-tissue massage using specialized heated herbal powders. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "treatment-for-sinusitis-allergies-and-chronic-migraines",
        "groupSlug": "eye-ear-head-rejuvenation",
        "title": "Treatment for Sinusitis, Allergies & Chronic Migraines",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Nasya medicated nasal drops to clear upper respiratory channels and sinus blocks. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "garbhasanskar-class-mindful-pregnancy-and-prenatal-care",
        "groupSlug": "maternal-pediatrics-custom-services",
        "title": "Garbhasanskar Class - Mindful Pregnancy and Prenatal Care",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Comprehensive monthly prenatal tracking, tailored diet charts, and mantra alignment. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "swarnaprashana-kids-immunity-and-brain-boosting-programme",
        "groupSlug": "maternal-pediatrics-custom-services",
        "title": "Swarnaprashana Kids Immunity and Brain Boosting Programme",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Monthly immunization using bio-available liquid gold, honey, and memory herbs. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "targeted-muscle-rejuvenation-and-tissue-strengthening",
        "groupSlug": "maternal-pediatrics-custom-services",
        "title": "Targeted Muscle Rejuvenation and Tissue Strengthening",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Pichu oil pooling and Abhyangam to combat progressive muscle wasting and weakness. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "treatment-for-cervical-spondylosis-and-nagging-neck-pain",
        "groupSlug": "orthopedics-non-surgical-pain-management",
        "title": "Treatment for Cervical Spondylosis and Nagging Neck Pain",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Greeva Basti cervical oil pooling to strengthen compressed nerve roots naturally. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "advanced-ayurvedic-treatment-for-chronic-psoriasis",
        "groupSlug": "skin-hair-advanced-blood-purification",
        "title": "Advanced Ayurvedic Treatment for Chronic Psoriasis",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Leech therapy combined with Takradhara to eliminate scalp scaling and scaling skin. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "sterile-and-clinically-monitored-panchakarma-protocols",
        "groupSlug": "skin-hair-advanced-blood-purification",
        "title": "Sterile and Clinically Monitored Panchakarma Protocols",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Emphasizing Gold Medalist Dr. Purva Verma's commitment to high hygiene standards. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "neuro-protective-therapies-for-memory-and-mental-clarity",
        "groupSlug": "stress-sleep-mental-wellness",
        "title": "Neuro-Protective Therapies for Memory and Mental Clarity",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Shirodhara and specialized nerve-strengthening remedies to prevent cognitive decline. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "treatment-for-sciatica-nerve-pain-and-lumbar-bulges",
        "groupSlug": "orthopedics-non-surgical-pain-management",
        "title": "Treatment for Sciatica Nerve Pain and Lumbar Bulges",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Agnikarma and Viddhakarma to provide rapid, non-surgical radiculopathy relief. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue-nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "systemic-blood-purification-and-toxic-fluid-cleanse",
        "groupSlug": "skin-hair-advanced-blood-purification",
        "title": "Systemic Blood Purification and Toxic Fluid Cleanse",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Siraveda (bloodletting) to detoxify blood tissue and eliminate deep dermal allergens. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "ayurvedic-ear-treatment-for-tinnitus-and-earaches",
        "groupSlug": "eye-ear-head-rejuvenation",
        "title": "Ayurvedic Ear Treatment for Tinnitus and Earaches",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Karnapurna and Karnaswedan ear oil pouring followed by gentle herbal steam. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "managing-pcos-and-hormonal-imbalances-naturally",
        "groupSlug": "maternal-pediatrics-custom-services",
        "title": "Managing PCOS and Hormonal Imbalances Naturally",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Customized enemas and Therapeutic Diet Charts to regulate irregular periods cycles. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist. Call Now (094249 39180) Image Link",
        "highlights": [],
        "images": []
    },
    {
        "slug": "advanced-ocular-therapy-for-vision-correction-and-dry-eyes",
        "groupSlug": "eye-ear-head-rejuvenation",
        "title": "Advanced Ocular Therapy for Vision Correction & Dry Eyes",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Netra Tarpana, Seka, and Bidalaka paste applications to strengthen optic nerves. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "non-surgical-advanced-rheumatoid-arthritis-rehabilitation",
        "groupSlug": "orthopedics-non-surgical-pain-management",
        "title": "Non-Surgical Advanced Rheumatoid Arthritis Rehabilitation",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Comprehensive pain clinic combinations of Agnikarma, Viddhakarma, and Swedana. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "clinical-sterility-in-traditional-alternative-bio-therapies",
        "groupSlug": "maternal-pediatrics-custom-services",
        "title": "Clinical Sterility in Traditional Alternative Bio-Therapies",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Highlighting hospital-grade care during leech therapy and pulse diagnostics. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "treatment-for-muscle-swelling-and-localized-trauma",
        "groupSlug": "orthopedics-non-surgical-pain-management",
        "title": "Treatment for Muscle Swelling and Localized Trauma",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Sthanika Dhara decoction pouring mixed with anti-inflammatory herbal poultices. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "ayurvedic-medicine-home-delivery-across-greater-kolkata",
        "groupSlug": "maternal-pediatrics-custom-services",
        "title": "Ayurvedic Medicine Home Delivery Across Greater Kolkata",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Hassle-free doorstep delivery of premium authentic brands like Kottakkal and Vaidyaratnam. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist. Call Now (094249 39180) Image Link",
        "highlights": [],
        "images": []
    },
    {
        "slug": "therapeutic-yoga-and-pranayama-for-metabolic-health",
        "groupSlug": "stress-sleep-mental-wellness",
        "title": "Therapeutic Yoga and Pranayama for Metabolic Health",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Customized breathing exercises and asanas to balance systemic Vata and Kapha. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "neuro-muscular-rehabilitation-and-paralysis-management",
        "groupSlug": "orthopedics-non-surgical-pain-management",
        "title": "Neuro-Muscular Rehabilitation and Paralysis Management",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Deep tissue Abhyangam and tailam applications to restore lost motor functions safely. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "ayurvedic-foot-therapy-for-sleep-and-stress-elimination",
        "groupSlug": "stress-sleep-mental-wellness",
        "title": "Ayurvedic Foot Therapy for Sleep and Stress Elimination",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Padabhyangam foot massage using a traditional Kansa metal wand and herbal ghee. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "treatment-for-frozen-shoulder-and-rotator-cuff-rigid-stiffness",
        "groupSlug": "orthopedics-non-surgical-pain-management",
        "title": "Treatment for Frozen Shoulder & Rotator Cuff Rigid Stiffness",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Prashta Basti shoulder joint oil pooling to fully restore movement range. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue-nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "treatment-for-chronic-bloating-gas-and-hyperacidity",
        "groupSlug": "digestive-detox-lifestyle-management",
        "title": "Treatment for Chronic Bloating, Gas, and Hyperacidity",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Deep gastrointestinal corrections to permanently balance the internal digestive fire. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "strengthening-lung-capacity-and-respiratory-defense",
        "groupSlug": "eye-ear-head-rejuvenation",
        "title": "Strengthening Lung Capacity and Respiratory Defense",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Dhoompan herbal smoke inhalation to flush stagnant Kapha from bronchial channels. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "treatment-for-under-eye-dark-circles-and-digital-puffiness",
        "groupSlug": "eye-ear-head-rejuvenation",
        "title": "Treatment for Under-Eye Dark Circles & Digital Puffiness",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Combining Netra Bidalaka paste and custom herbal eye bandaging treatments safely. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "deep-respiratory-detoxification-via-medicated-nasal-drops",
        "groupSlug": "eye-ear-head-rejuvenation",
        "title": "Deep Respiratory Detoxification via Medicated Nasal Drops",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Nasya therapy to protect chronic asthma patients from winter pollution spikes. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "ayurvedic-weight-loss-therapy-and-subcutaneous-fat-breakdown",
        "groupSlug": "digestive-detox-lifestyle-management",
        "title": "Ayurvedic Weight Loss Therapy & Subcutaneous Fat Breakdown",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Udwartana powder massage to naturally accelerate slow sluggish metabolic rates. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "ear-infection-itching-and-stubborn-wax-removal",
        "groupSlug": "eye-ear-head-rejuvenation",
        "title": "Ear Infection, Itching, and Stubborn Wax Removal",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Karnadhoopan ear fumigation utilizing sterile warm medicinal herbal smoke. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "treatment-for-lower-back-pain-and-lumbar-spondylosis",
        "groupSlug": "orthopedics-non-surgical-pain-management",
        "title": "Treatment for Lower Back Pain and Lumbar Spondylosis",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Kati Basti spinal oil pooling to strengthen vertebral muscles naturally. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue-nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "holistic-physical-rehabilitation-and-motor-nerve-support",
        "groupSlug": "orthopedics-non-surgical-pain-management",
        "title": "Holistic Physical Rehabilitation and Motor Nerve Support",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Marma activation and tissue-nourishing bastis to enhance independent mobility. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "swarnaprashana-annual-immunity-booster-for-children",
        "groupSlug": "maternal-pediatrics-custom-services",
        "title": "Swarnaprashana Annual Immunity Booster for Children",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Liquid gold and brain-boosting herbal drops to protect kids from winter ailments. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "treatment-for-severe-neck-stiffness-and-vertigo",
        "groupSlug": "eye-ear-head-rejuvenation",
        "title": "Treatment for Severe Neck Stiffness and Vertigo",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Greeva Basti neck oil pooling paired with Vata-pacifying herbal remedies. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue-nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "conserving-inner-body-energy-and-reversing-adrenal-burnout",
        "groupSlug": "stress-sleep-mental-wellness",
        "title": "Conserving Inner Body Energy and Reversing Adrenal Burnout",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Rejuvenating Dhara liquid pouring to restore systemic stamina and tissue vitality. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "advanced-treatment-for-chronic-acne-and-facial-pigmentation",
        "groupSlug": "skin-hair-advanced-blood-purification",
        "title": "Advanced Treatment for Chronic Acne and Facial Pigmentation",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Sterile leech therapy to safely purify facial blood channels and eliminate blemishes. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "panchakarma-winter-detoxification-and-body-reset-package",
        "groupSlug": "digestive-detox-lifestyle-management",
        "title": "Panchakarma Winter Detoxification and Body Reset Package",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Ritu Shodhana seasonal cleansing to balance internal doshas before the new year. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "targeted-treatment-for-calcaneal-spurs-and-heel-trauma",
        "groupSlug": "orthopedics-non-surgical-pain-management",
        "title": "Targeted Treatment for Calcaneal Spurs and Heel Trauma",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Precise Agnikarma thermal cauterization to provide drug-free, immediate pain relief. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist.",
        "highlights": [],
        "images": []
    },
    {
        "slug": "ayurvedic-medicine-home-doorstep-delivery-in-kolkata",
        "groupSlug": "maternal-pediatrics-custom-services",
        "title": "Ayurvedic Medicine Home Doorstep Delivery in Kolkata",
        "shortDescription": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for...",
        "description": "Discover how Swasthyaveda Healthcare clinic in Lake Town, Kolkata, provides advanced, root-cause clinical care for our community. Fast clinic pharmacy delivery of authentic Kottakkal and Dhootapapeshwar remedies. Under the direct clinical supervision of Gold Medalist doctor Dr. Purva Verma (BAMS, MD Ayurveda), our center matches structural wellness goals with natural therapies to fully resolve chronic illnesses safely. Our clinical framework integrates deep-acting herbal medicines with specialized external Panchakarma modalities tailored strictly to your individual body type. This dynamic medical model addresses complex structural conditions like knee pain, neurological spasms, skin disorders, and high stress by restoring deep hormonal and systemic harmony naturally. Avoid long-term dependency on heavy synthetic drugs or complex surgical pathways. Our fully operational clinic near Laketown Yes Bank provides a sterile, modern, and deeply compassionate medical environment for patients throughout Greater Kolkata, Salt Lake, and Dum Dum corridors. Every treatment protocol features specialized tissue nourishing components designed to boost your daily physical energy, restore full range of joint movement, and build robust lifelong structural immunity effortlessly. Reclaim your natural state of physical energy and long-term vitality safely under the care of an MD Ayurveda specialist. Call Now (094249 39180) Image Link",
        "highlights": [],
        "images": []
    }
];

export default servicesData;
